#include "engine/engine.hpp"

enum AudioResourceDefs :  AudioResource {			// Index into AudioData.sounds
	AUDIO_RSC_TOAST_NOTIFY,
	AUDIO_RSC_JUMP,
	AUDIO_RSC_BOOM,
	AUDIO_RSC_FUSE,
	AUDIO_RSC_DOOR_OPEN,
	AUDIO_RSC_AMBIENT,
	AUDIO_RSC_WIND
};

const auto SFX_TOAST_NOTIFY = SoundFXFlag_FromResource(AUDIO_RSC_TOAST_NOTIFY);
const auto SFX_JUMP = SoundFXFlag_FromResource(AUDIO_RSC_JUMP);
const auto SFX_BOOM = SoundFXFlag_FromResource(AUDIO_RSC_BOOM);
const auto SFX_FUSE = SoundFXFlag_FromResource(AUDIO_RSC_FUSE);
const auto SFX_DOOR_OPEN = SoundFXFlag_FromResource(AUDIO_RSC_DOOR_OPEN);
const auto SFX_TOGGLE_AMBIENT = SoundFXFlag_FromResource(AUDIO_RSC_AMBIENT);
const auto SFX_TOGGLE_WIND = SoundFXFlag_FromResource(AUDIO_RSC_WIND);

enum GraphicResourceDefs : GraphicResource {	
	GRAPHIC_RSC_BARREL_CIGARETTE_IDLE,			// Index into RenderData.graphics
	GRAPHIC_RSC_BARREL_CIGARETTE_EXPLODE,		
	GRAPHIC_RSC_BARREL_KURT_IDLE,		
	GRAPHIC_RSC_BARREL_KURT_EXPLODE,
	GRAPHIC_RSC_BARREL_TERRORIST_IDLE,		
	GRAPHIC_RSC_BARREL_TERRORIST_EXPLODE,
	GRAPHIC_RSC_BACKGROUND,
	GRAPHIC_RSC_PLAYER_WALK_LEFT,
	GRAPHIC_RSC_PLAYER_WALK_RIGHT,
	GRAPHIC_RSC_PLAYER_IDLE_LEFT,
	GRAPHIC_RSC_PLAYER_IDLE_RIGHT,
	GRAPHIC_RSC_GRASS_FLOOR,
	GRAPHIC_RSC_BARREL_DEFUSED,
	GRAPHIC_RSC_LADYBIRD_IDLE_LEFT,
	GRAPHIC_RSC_LADYBIRD_IDLE_RIGHT,
	GRAPHIC_RSC_LADYBIRD_WALK_LEFT,
	GRAPHIC_RSC_LADYBIRD_WALK_RIGHT,
	GRAPHIC_RSC_LADYBIRD_SHOCKED,
	GRAPHIC_RSC_LADYBIRD_FLIGHT
};
